/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as ApiGeocodeRouteImport } from './routes/api/geocode'
import { Route as ApiPlacesRouteImport } from './routes/api/places'
import { Route as ApiRatesRouteImport } from './routes/api/rates'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeocodeRoute = ApiGeocodeRouteImport.update({
  id: '/api/geocode',
  path: '/api/geocode',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlacesRoute = ApiPlacesRouteImport.update({
  id: '/api/places',
  path: '/api/places',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRatesRoute = ApiRatesRouteImport.update({
  id: '/api/rates',
  path: '/api/rates',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacidad': typeof PrivacidadRoute
  '/api/geocode': typeof ApiGeocodeRoute
  '/api/places': typeof ApiPlacesRoute
  '/api/rates': typeof ApiRatesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacidad': typeof PrivacidadRoute
  '/api/geocode': typeof ApiGeocodeRoute
  '/api/places': typeof ApiPlacesRoute
  '/api/rates': typeof ApiRatesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacidad': typeof PrivacidadRoute
  '/api/geocode': typeof ApiGeocodeRoute
  '/api/places': typeof ApiPlacesRoute
  '/api/rates': typeof ApiRatesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/privacidad' | '/api/geocode' | '/api/places' | '/api/rates'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/privacidad' | '/api/geocode' | '/api/places' | '/api/rates'
  id:
    | '__root__'
    | '/'
    | '/privacidad'
    | '/api/geocode'
    | '/api/places'
    | '/api/rates'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacidadRoute: typeof PrivacidadRoute
  ApiGeocodeRoute: typeof ApiGeocodeRoute
  ApiPlacesRoute: typeof ApiPlacesRoute
  ApiRatesRoute: typeof ApiRatesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/geocode': {
      id: '/api/geocode'
      path: '/api/geocode'
      fullPath: '/api/geocode'
      preLoaderRoute: typeof ApiGeocodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/places': {
      id: '/api/places'
      path: '/api/places'
      fullPath: '/api/places'
      preLoaderRoute: typeof ApiPlacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rates': {
      id: '/api/rates'
      path: '/api/rates'
      fullPath: '/api/rates'
      preLoaderRoute: typeof ApiRatesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacidadRoute: PrivacidadRoute,
  ApiGeocodeRoute: ApiGeocodeRoute,
  ApiPlacesRoute: ApiPlacesRoute,
  ApiRatesRoute: ApiRatesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
